<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2a01b80a25e726e8ef38cdfb81d40a80
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2a01b80a25e726e8ef38cdfb81d40a80::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2a01b80a25e726e8ef38cdfb81d40a80::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2a01b80a25e726e8ef38cdfb81d40a80::$classMap;

        }, null, ClassLoader::class);
    }
}
